on:
  issues:
    types: [opened]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-praser@dev
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/test-1.yml
          issue-body: ${{ github.event.issue.body }}
      
      - run: cat ${HOME}/issue-parser-result.json
      
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > output.json
      - run: cat output.json
      
      - run: echo '${{ steps.issue-parser.outputs.issueparser_favorite_color }}'


      - uses: peter-evans/close-issue@v1
        with:
          comment: ${{ steps.issue-parser.outputs.jsonString }}
